Restructure the project directory structure and build procedure
theia-ide/vscode-trace-extension pull request #18
Opened 2021-03-11 16:10 UTC by bhufmann

- Move the vscode extension into directory vscode-trace-extension
- Move react app running in webview into directory vscode-trace-webviews
- Use lerna to build
- Build the extension with command "yarn"
- README updates
- Update Copyright information
- Some minor clean-ups

Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>

2021-03-11 19:24 UTC, tahini requested changes
This is awesome!! No more symlinking scripts! Thanks for finding this.

The 2 workspaces work great too!

Just a small comment about the yarn link commands which do not work exactly as described in the README here

2021-03-11 20:34 UTC, bhufmann commented on README.md
> +yarn link tsp-typescript-client
Yes, true. I'll update it.

2021-03-11 20:35 UTC, bhufmann commented on README.md
> +yarn link "@trace-viewer/base"
I'll update

2021-03-11 20:38 UTC, bhufmann commented
> This is awesome!! No more symlinking scripts! Thanks for finding this.
> 
Behind the scenes it actually does symlinks for you. BTW, you can use it to run libraries from source code (e.g. use local timeline-chart in theia-trace-extension). Don't forget to yarn unlink <package> when not needed anymore.

2021-03-12 01:14 UTC, tahini approved these changes
Great addition, thank you!

2021-03-12 14:31 UTC, MatthewKhouzam approved these changes
This looks good to me.

2021-03-12 14:44 UTC, merged