Fix for vsix package not finding some dependencies on activation
theia-ide/vscode-trace-extension pull request #53
Opened 2022-09-13 17:56 UTC by ngondalia

- Used webpack to package the extension
- Added additional options to TS compiler config

2022-09-13 17:58 UTC, ngondalia commented
Questions for the devs.. Is there a licensing file i should put anywhere that includes the copyright for blackberry?

2022-09-14 19:35 UTC, bhufmann requested changes
Thanks for the contribution. It works and I'm able to install the vsix extension to VsCode without an error.

I have some minor comments. Please also update your git commit message:

- Have a title for the commit
- Describe the change (you can use your bullet points)
- What it actually fixes
- Add a signed-off-by: Signed-off-by: FirstName LastName <email address>

2022-09-14 19:35 UTC, bhufmann commented on common-tsconfig.json
>  }
I get a marker that a newline  is missing at the end of file. Could please add it?

2022-09-14 19:35 UTC, bhufmann commented on vscode-trace-extension/.vscodeignore
> +src
add newline at the end of file

2022-09-14 19:35 UTC, bhufmann commented on vscode-trace-extension/tsconfig.json
>  }
newline at the end of file

2022-09-14 19:35 UTC, bhufmann commented on vscode-trace-extension/webpack.config.js
> +module.exports = config;
newline at the end of file

2022-09-15 00:11 UTC, bhufmann commented
I noticed a problem when running it from development environment. Using the launch configuration `Launch Extension` (press `F5`) to start vscode with the trace viewer extension in debug mode, I get the error message below when switching to the `trace viewer` view. Could you please fix it with your changes? Thanks!

![image](https://user-images.githubusercontent.com/413424/190283909-9a771d38-7b44-425e-b7d8-040b393ba945.png)

2022-09-15 15:02 UTC, ngondalia commented
> 

The error you are seeing is likely due to webpack script was not ran. I will add it under prepare script so it gets ran by default when you run yarn.

2022-09-15 15:04 UTC, ngondalia commented
> Questions for the devs.. Is there a licensing file i should put anywhere that includes the copyright for blackberry?

Any input on this?

2022-09-15 19:34 UTC, bhufmann commented
> > Questions for the devs.. Is there a licensing file i should put anywhere that includes the copyright for blackberry?
> 
> Any input on this?

I would suggest the LICENSE file in the root directory of the repository. WDYT?

2022-09-15 19:40 UTC, bhufmann approved these changes
It looks good to me. Thanks a lot for this fix. Do you want me to merge it or do you want to update the License file in this PR first?

2022-09-15 19:45 UTC, ngondalia commented
> It looks good to me. Thanks a lot for this fix. Do you want me to merge it or do you want to update the License file in this PR first?

Let me update the license file first, and then you can merge it.

2022-09-15 20:56 UTC, ngondalia commented
> > > Questions for the devs.. Is there a licensing file i should put anywhere that includes the copyright for blackberry?
> > 
> > 
> > Any input on this?
> 
> I would suggest the LICENSE file in the root directory of the repository. WDYT?

I have update the license file. Let me know if that works for you. Thanks!

2022-09-16 14:00 UTC, MatthewKhouzam approved these changes
Looks great to me! Thanks!

2022-09-16 14:20 UTC, merged